name: Deploy Frontend to Azure Web App

on:
  workflow_dispatch:
  # Push trigger comentado para evitar deploy autom치tico no primeiro commit
  # Descomente as linhas abaixo se quiser deploy autom치tico em futuros pushes:
  # push:
  #   branches:
  #     - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Create production environment file
        working-directory: ./frontend
        run: |
          echo "NEXT_PUBLIC_API_URL=https://expandev-02.azurewebsites.net/api/v1" > .env.production
          cat .env.production

      - name: Update next.config.mjs with backend URL
        working-directory: ./frontend
        run: |
          cat > next.config.mjs << 'EOF'
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            output: 'standalone',
            async rewrites() {
              return [
                {
                  source: '/api/:path*',
                  destination: 'https://expandev-02.azurewebsites.net/api/:path*',
                },
              ];
            },
          };
          
          export default nextConfig;
          EOF

      - name: npm install and build
        working-directory: ./frontend
        run: |
          npm install
          NEXT_PUBLIC_API_URL=https://expandev-02.azurewebsites.net/api/v1 npm run build
          
          # Verificar se standalone foi criado
          echo "Checking .next directory:"
          ls -la .next/
          
          # Copiar arquivos est치ticos necess치rios
          cp -R ./public ./.next/standalone/public
          cp -R ./.next/static ./.next/standalone/.next/static
          
          echo "Standalone directory contents:"
          ls -la .next/standalone/

      - name: Zip artifact for deployment
        working-directory: ./frontend
        run: |
          cd .next/standalone
          zip -r ../../release.zip .
          cd ../..
          echo "Release zip created"
          ls -la release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: ./frontend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Unzip artifact for deployment
        run: |
          echo "Files before unzip:"
          ls -la
          unzip release.zip
          echo "Unzipped contents:"
          ls -la
          echo "Checking for package.json:"
          if [ -f "package.json" ]; then
            echo "package.json found!"
            head -5 package.json
          else
            echo "ERROR: package.json not found!"
          fi
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'expandev-01'
          package: .
          startup-command: 'node server.js'
        env:
          SCM_DO_BUILD_DURING_DEPLOYMENT: 'false'
          WEBSITE_RUN_FROM_PACKAGE: '0'
          ENABLE_ORYX_BUILD: 'false'